# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hat_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('brim_curvature', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_hat', to='brain.Hat')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circumference', models.IntegerField(default=0)),
                ('diameter_length', models.CharField(max_length=55)),
                ('diameter_width', models.CharField(max_length=55)),
                ('side_height_front', models.CharField(max_length=55)),
                ('side_height_middle', models.CharField(max_length=55)),
                ('side_height_back', models.CharField(max_length=55)),
                ('front_height', models.CharField(max_length=55)),
                ('brim_length', models.CharField(max_length=55)),
                ('brim_width', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('shipping_choice', models.IntegerField()),
                ('shipping_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hat_choice', models.ManyToManyField(to='brain.Hat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Address', serialize=False, to='brain.User')),
                ('street_address', models.CharField(max_length=55)),
                ('Street_address2', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='brain.User'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Measurement', to='brain.User'),
        ),
        migrations.AddField(
            model_name='hat_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hat_Order', to='brain.User'),
        ),
    ]
